"""
Dashboard router.

Provides a consolidated view of conversation data stored in the local
SQLite database generated by the init sync workflow. The endpoints return
aggregated stats for devices, 客服, customers, and recent conversations so
the UI can render a quick status overview.
"""

from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, HTTPException, Query

from services.federated_reads import federated_reads
from wecom_automation.database.schema import get_connection, get_db_path

router = APIRouter()


def _open_db(db_path: Optional[str]) -> Tuple[Any, str]:
    """
    Open the SQLite database and ensure it exists.

    Args:
        db_path: Optional override path supplied by the caller.

    Returns:
        Tuple of (connection, resolved_path_str)
    """
    resolved_path = get_db_path(db_path)
    if not resolved_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Database not found at {resolved_path}",
        )
    return get_connection(str(resolved_path)), str(resolved_path)


def _fetch_stats(conn) -> Dict[str, Any]:
    """Collect overall table counts and message type breakdown."""
    cursor = conn.cursor()
    stats: Dict[str, Any] = {}

    for table in ("devices", "kefus", "customers", "messages", "images"):
        cursor.execute(f"SELECT COUNT(*) as count FROM {table}")
        row = cursor.fetchone()
        stats[table] = row["count"] if row else 0

    cursor.execute(
        """
        SELECT message_type, COUNT(*) as count
        FROM messages
        GROUP BY message_type
        """
    )
    stats["messages_by_type"] = {row["message_type"]: row["count"] for row in cursor.fetchall()}

    return stats


def _fetch_last_activity(conn) -> Optional[str]:
    """Get the most recent activity timestamp from messages or entity updates."""
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT MAX(ts) as last_ts FROM (
            SELECT MAX(COALESCE(timestamp_parsed, created_at)) as ts FROM messages
            UNION ALL
            SELECT MAX(updated_at) FROM customers
            UNION ALL
            SELECT MAX(updated_at) FROM kefus
            UNION ALL
            SELECT MAX(updated_at) FROM devices
        )
        """
    )
    row = cursor.fetchone()
    return row["last_ts"] if row else None


def _fetch_devices(conn) -> List[Dict[str, Any]]:
    """Summaries per device with conversation coverage."""
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT
            d.id,
            d.serial,
            d.model,
            d.manufacturer,
            d.android_version,
            d.created_at,
            d.updated_at,
            (
                SELECT COUNT(DISTINCT kd.kefu_id) FROM kefu_devices kd
                WHERE kd.device_id = d.id
            ) AS kefu_count,
            (
                SELECT COUNT(DISTINCT c.id) FROM customers c
                JOIN kefus k ON c.kefu_id = k.id
                JOIN kefu_devices kd ON k.id = kd.kefu_id
                WHERE kd.device_id = d.id
            ) AS customer_count,
            (
                SELECT COUNT(*) FROM messages m
                JOIN customers c ON m.customer_id = c.id
                JOIN kefus k ON c.kefu_id = k.id
                JOIN kefu_devices kd ON k.id = kd.kefu_id
                WHERE kd.device_id = d.id
            ) AS message_count,
            (
                SELECT COUNT(*) FROM messages m
                JOIN customers c ON m.customer_id = c.id
                JOIN kefus k ON c.kefu_id = k.id
                JOIN kefu_devices kd ON k.id = kd.kefu_id
                WHERE kd.device_id = d.id AND m.is_from_kefu = 1
            ) AS sent_by_kefu,
            (
                SELECT COUNT(*) FROM messages m
                JOIN customers c ON m.customer_id = c.id
                JOIN kefus k ON c.kefu_id = k.id
                JOIN kefu_devices kd ON k.id = kd.kefu_id
                WHERE kd.device_id = d.id AND m.is_from_kefu = 0
            ) AS sent_by_customer,
            (
                SELECT MAX(COALESCE(m.timestamp_parsed, m.created_at))
                FROM messages m
                JOIN customers c ON m.customer_id = c.id
                JOIN kefus k ON c.kefu_id = k.id
                JOIN kefu_devices kd ON k.id = kd.kefu_id
                WHERE kd.device_id = d.id
            ) AS last_message_at
        FROM devices d
        ORDER BY d.created_at DESC
        """
    )
    return [dict(row) for row in cursor.fetchall()]


def _fetch_kefus(conn) -> List[Dict[str, Any]]:
    """Summaries per 客服, including coverage and last active customer."""
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT
            k.id,
            k.name,
            k.department,
            k.verification_status,
            (
                SELECT COUNT(*) FROM kefu_devices kd
                WHERE kd.kefu_id = k.id
            ) AS device_count,
            (
                SELECT COUNT(*) FROM customers c
                WHERE c.kefu_id = k.id
            ) AS customer_count,
            (
                SELECT COUNT(*) FROM messages m
                JOIN customers c ON m.customer_id = c.id
                WHERE c.kefu_id = k.id
            ) AS message_count,
            (
                SELECT COUNT(*) FROM messages m
                JOIN customers c ON m.customer_id = c.id
                WHERE c.kefu_id = k.id AND m.is_from_kefu = 1
            ) AS sent_by_kefu,
            (
                SELECT COUNT(*) FROM messages m
                JOIN customers c ON m.customer_id = c.id
                WHERE c.kefu_id = k.id AND m.is_from_kefu = 0
            ) AS sent_by_customer,
            (
                SELECT MAX(COALESCE(m.timestamp_parsed, m.created_at))
                FROM messages m
                JOIN customers c ON m.customer_id = c.id
                WHERE c.kefu_id = k.id
            ) AS last_message_at,
            (
                SELECT c.name FROM customers c
                WHERE c.kefu_id = k.id
                ORDER BY COALESCE(c.last_message_date, c.updated_at, c.created_at) DESC
                LIMIT 1
            ) AS last_customer_name,
            (
                SELECT c.channel FROM customers c
                WHERE c.kefu_id = k.id
                ORDER BY COALESCE(c.last_message_date, c.updated_at, c.created_at) DESC
                LIMIT 1
            ) AS last_customer_channel,
            (
                SELECT c.last_message_preview FROM customers c
                WHERE c.kefu_id = k.id
                ORDER BY COALESCE(c.last_message_date, c.updated_at, c.created_at) DESC
                LIMIT 1
            ) AS last_message_preview,
            (
                SELECT c.last_message_date FROM customers c
                WHERE c.kefu_id = k.id
                ORDER BY COALESCE(c.last_message_date, c.updated_at, c.created_at) DESC
                LIMIT 1
            ) AS last_message_date,
            k.created_at,
            k.updated_at
        FROM kefus k
        ORDER BY k.updated_at DESC
        """
    )

    # Enrich with devices list
    results = []
    for row in cursor.fetchall():
        item = dict(row)
        cursor.execute(
            """
            SELECT d.id, d.serial, d.model
            FROM devices d
            JOIN kefu_devices kd ON d.id = kd.device_id
            WHERE kd.kefu_id = ?
            ORDER BY kd.created_at DESC
            """,
            (item["id"],),
        )
        item["devices"] = [dict(d) for d in cursor.fetchall()]
        results.append(item)

    return results


def _fetch_recent_conversations(conn, limit: int = 50) -> List[Dict[str, Any]]:
    """Recent conversations ordered by last activity."""
    cursor = conn.cursor()
    cursor.execute(
        f"""
        SELECT
            c.id,
            c.name,
            c.channel,
            c.last_message_preview,
            c.last_message_date,
            c.updated_at,
            c.created_at,
            k.id AS kefu_id,
            k.name AS kefu_name,
            k.department AS kefu_department,
            (
                SELECT COUNT(*) FROM messages m
                WHERE m.customer_id = c.id
            ) AS message_count,
            (
                SELECT COUNT(*) FROM messages m
                WHERE m.customer_id = c.id AND m.is_from_kefu = 1
            ) AS sent_by_kefu,
            (
                SELECT COUNT(*) FROM messages m
                WHERE m.customer_id = c.id AND m.is_from_kefu = 0
            ) AS sent_by_customer,
            (
                SELECT MAX(COALESCE(m.timestamp_parsed, m.created_at))
                FROM messages m
                WHERE m.customer_id = c.id
            ) AS last_message_at
        FROM customers c
        JOIN kefus k ON c.kefu_id = k.id
        ORDER BY COALESCE(last_message_at, c.last_message_date, c.updated_at, c.created_at) DESC
        LIMIT ?
        """,
        (limit,),
    )
    return [dict(row) for row in cursor.fetchall()]


@router.get("/overview")
async def get_dashboard_overview(
    db_path: Optional[str] = Query(
        None,
        description="Optional override for the conversations database path.",
    ),
    limit: int = Query(
        50,
        ge=1,
        le=200,
        description="Maximum number of recent conversations to return.",
    ),
):
    """
    Return aggregated dashboard data for the current conversations database.

    Includes overall counts, per-device coverage, per-客服 summaries, and the
    most recent conversations across all synced devices.
    """
    if db_path is None:
        return federated_reads.get_dashboard_overview(limit=limit)

    conn, resolved_path = _open_db(db_path)
    try:
        stats = _fetch_stats(conn)
        last_updated = _fetch_last_activity(conn)
        devices = _fetch_devices(conn)
        kefus = _fetch_kefus(conn)
        recent_conversations = _fetch_recent_conversations(conn, limit=limit)

        return {
            "db_path": resolved_path,
            "last_updated": last_updated,
            "stats": stats,
            "devices": devices,
            "kefus": kefus,
            "recent_conversations": recent_conversations,
        }
    finally:
        conn.close()


def _fetch_message_timeseries(
    conn,
    kefu_ids: Optional[List[int]] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    granularity: str = "day",
) -> Dict[str, Any]:
    """
    Fetch message counts over time, optionally filtered by 客服 and date range.

    Args:
        conn: Database connection
        kefu_ids: Optional list of kefu IDs to filter by
        start_date: Optional start date (ISO format)
        end_date: Optional end date (ISO format)
        granularity: 'hour', 'day', 'week', or 'month'

    Returns:
        Dict with time series data for total, incoming, outgoing, and per-kefu
    """
    cursor = conn.cursor()

    # Determine date formatting based on granularity
    date_formats = {
        "hour": "%Y-%m-%d %H:00",
        "day": "%Y-%m-%d",
        "week": "%Y-W%W",
        "month": "%Y-%m",
    }
    date_format = date_formats.get(granularity, "%Y-%m-%d")

    # Build base query conditions
    conditions = []
    params: List[Any] = []

    if start_date:
        conditions.append("COALESCE(m.timestamp_parsed, m.created_at) >= ?")
        params.append(start_date)

    if end_date:
        conditions.append("COALESCE(m.timestamp_parsed, m.created_at) <= ?")
        params.append(end_date)

    if kefu_ids:
        placeholders = ",".join(["?" for _ in kefu_ids])
        conditions.append(f"k.id IN ({placeholders})")
        params.extend(kefu_ids)

    where_clause = " AND ".join(conditions) if conditions else "1=1"

    # Query for overall totals by time period
    cursor.execute(
        f"""
        SELECT 
            strftime('{date_format}', COALESCE(m.timestamp_parsed, m.created_at)) as time_bucket,
            COUNT(*) as total,
            SUM(CASE WHEN m.is_from_kefu = 1 THEN 1 ELSE 0 END) as outgoing,
            SUM(CASE WHEN m.is_from_kefu = 0 THEN 1 ELSE 0 END) as incoming
        FROM messages m
        JOIN customers c ON m.customer_id = c.id
        JOIN kefus k ON c.kefu_id = k.id
        WHERE {where_clause}
        GROUP BY time_bucket
        ORDER BY time_bucket ASC
        """,
        params,
    )

    overall_data = []
    for row in cursor.fetchall():
        overall_data.append(
            {
                "time": row["time_bucket"],
                "total": row["total"],
                "outgoing": row["outgoing"],
                "incoming": row["incoming"],
            }
        )

    # Query for per-kefu breakdown
    kefu_series: Dict[int, List[Dict[str, Any]]] = {}

    # Get list of kefus to include
    if kefu_ids:
        target_kefu_ids = kefu_ids
    else:
        cursor.execute("SELECT id FROM kefus")
        target_kefu_ids = [row["id"] for row in cursor.fetchall()]

    for kefu_id in target_kefu_ids:
        kefu_conditions = conditions.copy()
        kefu_params = params.copy()

        # Replace kefu filter with specific kefu
        if kefu_ids:
            # Remove the IN clause and add specific kefu
            kefu_conditions = [c for c in kefu_conditions if "k.id IN" not in c]
            kefu_params = kefu_params[: len(kefu_params) - len(kefu_ids)]

        kefu_conditions.append("k.id = ?")
        kefu_params.append(kefu_id)
        kefu_where = " AND ".join(kefu_conditions)

        cursor.execute(
            f"""
            SELECT 
                strftime('{date_format}', COALESCE(m.timestamp_parsed, m.created_at)) as time_bucket,
                COUNT(*) as total,
                SUM(CASE WHEN m.is_from_kefu = 1 THEN 1 ELSE 0 END) as outgoing,
                SUM(CASE WHEN m.is_from_kefu = 0 THEN 1 ELSE 0 END) as incoming
            FROM messages m
            JOIN customers c ON m.customer_id = c.id
            JOIN kefus k ON c.kefu_id = k.id
            WHERE {kefu_where}
            GROUP BY time_bucket
            ORDER BY time_bucket ASC
            """,
            kefu_params,
        )

        kefu_series[kefu_id] = []
        for row in cursor.fetchall():
            kefu_series[kefu_id].append(
                {
                    "time": row["time_bucket"],
                    "total": row["total"],
                    "outgoing": row["outgoing"],
                    "incoming": row["incoming"],
                }
            )

    # Get kefu names for the legend
    cursor.execute("SELECT id, name FROM kefus")
    kefu_names = {row["id"]: row["name"] for row in cursor.fetchall()}

    return {
        "overall": overall_data,
        "by_kefu": kefu_series,
        "kefu_names": kefu_names,
        "granularity": granularity,
    }


@router.get("/timeseries")
async def get_message_timeseries(
    db_path: Optional[str] = Query(
        None,
        description="Optional override for the conversations database path.",
    ),
    kefu_ids: Optional[str] = Query(
        None,
        description="Comma-separated list of kefu IDs to filter by.",
    ),
    start_date: Optional[str] = Query(
        None,
        description="Start date in ISO format (e.g., 2024-01-01).",
    ),
    end_date: Optional[str] = Query(
        None,
        description="End date in ISO format (e.g., 2024-12-31).",
    ),
    granularity: str = Query(
        "day",
        description="Time granularity: 'hour', 'day', 'week', or 'month'.",
    ),
):
    """
    Return time series data for message counts.

    Provides overall totals and per-客服 breakdowns, with incoming/outgoing splits.
    Useful for trend analysis and comparison charts.
    """
    if db_path is None:
        parsed_kefu_ids = None
        if kefu_ids:
            try:
                parsed_kefu_ids = [int(x.strip()) for x in kefu_ids.split(",")]
            except ValueError:
                raise HTTPException(
                    status_code=400,
                    detail="kefu_ids must be comma-separated integers",
                )
        return federated_reads.get_message_timeseries(
            kefu_ids=parsed_kefu_ids,
            start_date=start_date,
            end_date=end_date,
            granularity=granularity,
        )

    conn, resolved_path = _open_db(db_path)
    try:
        parsed_kefu_ids = None
        if kefu_ids:
            try:
                parsed_kefu_ids = [int(x.strip()) for x in kefu_ids.split(",")]
            except ValueError:
                raise HTTPException(
                    status_code=400,
                    detail="kefu_ids must be comma-separated integers",
                )

        timeseries = _fetch_message_timeseries(
            conn,
            kefu_ids=parsed_kefu_ids,
            start_date=start_date,
            end_date=end_date,
            granularity=granularity,
        )

        return {
            "db_path": resolved_path,
            **timeseries,
        }
    finally:
        conn.close()
